(in-package #:axllm/tests)

(defun run-builder-tests ()
  "Exercise production builders against shared expectations, not test builders."
  (let ((count 0))
    (dolist (suite '("signature" "schema"))
      (dolist (path (fixture-files suite))
        (let* ((fixture (read-fixture path)) (spec (ax:jget fixture "signature_spec")))
          (when (hash-table-p spec)
            (let ((kind (ax:jget fixture "kind")))
              (cond
                ((equal kind "signature_error")
                 (let ((failure (handler-case (progn (ax:signature-from-spec spec) nil)
                                  (ax:signature-error (condition) condition))))
                   (assert failure)
                   (assert (search (ax:jget fixture "expected_error_contains" "")
                                   (princ-to-string failure)))))
                ((equal kind "signature")
                 (let ((signature (ax:signature-from-spec spec)))
                   (assert-equal (signature-payload signature) (ax:jget fixture "expected_signature") "public builder")
                   (unless (eq (ax:jget fixture "expected_to_string") :null)
                     (assert-equal (ax:signature-string signature) (ax:jget fixture "expected_to_string") "builder rendering"))))
                ((equal kind "json_schema")
                 (assert-equal
                  (ax:json-schema (ax:signature-from-spec spec)
                                  :side (if (equal (ax:jget fixture "target" "outputs") "inputs") :input :output)
                                  :title (ax:jget fixture "schema_title" "Schema")
                                  :options (ax:jget fixture "schema_options" nil))
                  (ax:jget fixture "expected_schema") "builder schema"))
                (t (fail "Unrecognized builder fixture kind: ~A" kind))))
            (incf count)))))
    (let* ((signature (ax:s :inputs (ax:object "query" (ax:f "string" :cache t))
                            :outputs (ax:object "scores" (ax:f "number" :array t :min 0 :max 3 :optional t))))
           (schema (ax:json-schema signature :side :output)))
      (assert-equal (ax:jget schema "required") #() "optional builder field")
      (assert-equal (ax:jget (ax:jget (ax:jget schema "properties") "scores") "items")
                    (ax:object "type" "number" "minimum" 0 "maximum" 3
                               "description" "Minimum value: 0, maximum value: 3") "array constraints")
      (assert (eq (ax:jget (aref (ax:signature-fields signature) 0) "isCached") ax:true)))
    (format t "Public builder: ~D shared fixtures and native construction PASS~%" count)))
