;;;; Run through asdf:test-system "axllm".
;;;; No network, provider, tracer SDK, or test-framework dependency.

(defpackage #:axllm/telemetry-tests
  (:use #:cl #:axllm)
  (:export #:run-telemetry-tests))
(in-package #:axllm/telemetry-tests)

(defvar *checks* 0)
(defun check (value &optional (message "telemetry assertion failed"))
  (incf *checks*)
  (unless value (error "~A" message)))

(defun scripted-meter (&key fail-create fail-record)
  "Independent scripted meter: capture actual factory calls and actual observations.
Its labels must survive the public JSON encoder, not a facade-private copier."
  (let ((creations nil) (observations nil))
    (labels ((create (kind name options)
               (when fail-create (error "meter factory failed"))
               (push (list kind name (parse-json (encode-json options))) creations)
               (flet ((observe (method value labels)
                        (when fail-record (error "exporter failed"))
                        (push (list name method value (parse-json (encode-json labels))) observations)
                        :null))
                 (object "add" (lambda (value labels) (observe "add" value labels))
                         "record" (lambda (value labels) (observe "record" value labels))))))
      (values (object "createCounter" (lambda (name options) (create "counter" name options))
                      "createHistogram" (lambda (name options) (create "histogram" name options))
                      "createGauge" (lambda (name options) (create "gauge" name options)))
              (lambda () (reverse observations))
              (lambda () (reverse creations))))))

(defun test-globals-and-frames ()
  (check (eq true (get-global "signatureStrict")))
  (check (eq :null (get-global "debug")))
  (check (string= "" (funcall (get-global "functionResultFormatter") :null)))
  (check (string= "plain" (funcall (get-global "functionResultFormatter") "plain")))
  (check (string= (format nil "{~%  ~S: [~%    true,~%    null,~%    {}~%  ]~%}" "z")
                  (funcall (get-global "functionResultFormatter")
                           (object "z" (vector true :null (object))))))
  (let ((labels (object "logger" (copy-seq "label-not-hook"))))
    (set-global "customLabels" labels)
    (setf (char (jget labels "logger") 0) #\X)
    (let ((snapshot (globals-snapshot)))
      (setf (char (jget (jget snapshot "customLabels") "logger") 1) #\X))
    (check (equal "label-not-hook" (jget (get-global "customLabels") "logger"))))
  (setf (char (aref (jget (default-metrics-config) "enabledCategories") 0) 0) #\X
        (char (aref (jget (default-optimizer-metrics-config) "enabledCategories") 0) 0) #\X
        (char (jget (span-events) "GEN_AI_USAGE") 0) #\X
        (char (jget (span-attributes) "LLM_SYSTEM") 0) #\X)
  (check (equal "generation" (aref (jget (default-metrics-config) "enabledCategories") 0)))
  (check (equal "optimization" (aref (jget (default-optimizer-metrics-config) "enabledCategories") 0)))
  (check (equal "gen_ai.usage" (jget (span-events) "GEN_AI_USAGE")))
  (check (equal "gen_ai.system" (jget (span-attributes) "LLM_SYSTEM")))
  (let* ((callback (lambda (&rest ignored) (declare (ignore ignored)) :null))
         (meter (object "createCounter" callback))
         (labels (object "team" (copy-seq "native"))))
    (update-globals (object "meter" meter "logger" callback "customLabels" labels "debug" false))
    (setf (char (jget labels "team") 0) #\X)
    (check (equal "native" (jget (get-global "customLabels") "team")))
    (let ((snapshot (globals-snapshot)))
      (check (eq meter (jget snapshot "meter")))
      (check (eq callback (jget snapshot "logger")))
      (setf (gethash "debug" snapshot) true
            (gethash "team" (jget snapshot "customLabels")) "changed")
      (check (eq false (get-global "debug")))
      (check (equal "native" (jget (get-global "customLabels") "team"))))
    (check (handler-case (progn (update-globals (object "debug" true "typo" true)) nil)
             (ax-error () t)))
    (check (eq false (get-global "debug")))
    (let* ((base (object "z" 1 "nested" (object "values" (vector 2 3)) "a" true))
           (frame (make-runtime-hook-frame :resolved true))
           (framed (options-with-runtime-hook-frame base frame))
           (copied (copy-runtime-options framed))
           (cache (make-hash-table :test 'equal)))
      (check (eq :null (get-runtime-hook-frame base)))
      (check (eq frame (get-runtime-hook-frame copied)))
      (check (eq true (runtime-hook-frame-resolved frame)))
      (check (eq callback (jget (runtime-hook-frame-globals frame) "logger")))
      (check (eq meter (jget (runtime-hook-frame-globals frame) "meter")))
      (check (string= "{\"z\":1,\"nested\":{\"values\":[2,3]},\"a\":true}" (encode-json copied)))
      (check (string= (encode-json base) (encode-json framed)))
      (setf (gethash (encode-json base) cache) :hit)
      (check (eq :hit (gethash (encode-json copied) cache)))
      (check (eq :null (get-runtime-hook-frame (parse-json (encode-json copied)))))
      (setf (aref (jget (jget copied "nested") "values") 0) 99)
      (check (= 2 (aref (jget (jget base "nested") "values") 0)))
      (set-global "logger" :null)
      (check (eq callback (jget (runtime-hook-frame-globals frame) "logger")))
      (check (handler-case (progn (encode-json frame) nil) (ax-error () t))))
    (let* ((options (object "tracer" meter "onUsage" callback))
           (copy (copy-runtime-options options)))
      (check (eq meter (jget copy "tracer")))
      (check (eq callback (jget copy "onUsage")))
      (check (handler-case (progn (encode-json copy) nil) (ax-error () t)))))
  (let ((config (object "enabledCategories" (vector (copy-seq "streaming")) "samplingRate" 0)))
    (update-metrics-config config)
    (setf (char (aref (jget config "enabledCategories") 0) 0) #\X)
    (check (equal "streaming" (aref (jget (get-metrics-config) "enabledCategories") 0)))
    (let ((snapshot (get-metrics-config)))
      (setf (aref (jget snapshot "enabledCategories") 0) "changed")
      (check (equal "streaming" (aref (jget (get-metrics-config) "enabledCategories") 0))))
    (check (= 100 (jget (get-metrics-config) "maxLabelLength")))
    (check (= 0 (jget (get-metrics-config) "samplingRate"))))
  (let ((config (object "enabledCategories" (vector "pareto") "maxLabelLength" 7)))
    (update-optimizer-metrics-config config)
    (setf (aref (jget config "enabledCategories") 0) "changed")
    (let ((snapshot (get-optimizer-metrics-config)))
      (check (equal "pareto" (aref (jget snapshot "enabledCategories") 0)))
      (setf (aref (jget snapshot "enabledCategories") 0) "mutated"))
    (check (equal "pareto" (aref (jget (get-optimizer-metrics-config) "enabledCategories") 0)))
    (check (= 100 (jget (get-metrics-config) "maxLabelLength"))))
  (check (equal "{\"a\":\"last\",\"b\":\"second\"}"
                (encode-json (merge-custom-labels (object "a" "first") :null
                                                  (object "b" "second" "a" "last")))))
  (check (= 21 (hash-table-count (span-attributes))))
  (check (= 6 (hash-table-count (span-events))))
  (check (equal "gen_ai.usage.total_tokens" (jget (span-attributes) "LLM_USAGE_TOTAL_TOKENS")))
  (check (equal "gen_ai.usage" (jget (span-events) "GEN_AI_USAGE")))
  (reset-globals)
  (update-metrics-config (default-metrics-config))
  (update-optimizer-metrics-config (default-optimizer-metrics-config)))

(defun test-spans ()
  (let* ((ends 0)
         (raw (object "end" (lambda () (incf ends) (error "end failed"))
                      "isRecording" (lambda () (error "isRecording failed"))
                      "setAttribute" (lambda (&rest args) (declare (ignore args)) (error "attribute failed"))))
         (span (fail-open-span raw)))
    (check (eq false (span-call span "isRecording")))
    (check (eq :null (span-call span "setAttribute" "x" 1)))
    (span-call span "end")
    (span-call span "end")
    (check (= 1 ends)))
  (check (eq false (span-call :null "isRecording")))
  (check (eq false (span-call (fail-open-span (object "isRecording" (lambda () false))) "isRecording")))
  (check (eq true (span-call (fail-open-span (object "isRecording" (lambda () t))) "isRecording")))
  (check (eq :null (start-span-fail-open :null "absent")))
  (check (eq :null (start-span-fail-open (object "startSpan" (lambda (&rest args)
                                                                            (declare (ignore args)) (error "broken"))) "failed")))
  (let* ((parent (list :native-context)) (options (object "kind" 1)) (ends 0)
         (tracer (object "startSpan" (lambda (name supplied-options supplied-parent)
                                       (check (equal "test" name))
                                       (check (eq options supplied-options))
                                       (check (eq parent supplied-parent))
                                       (object "end" (lambda () (incf ends))))))
         (span (start-span-fail-open tracer "test" options parent)))
    (span-call span "end") (span-call span "end") (check (= 1 ends)))
  ;; Before/after callback failures, duplicate callback, no callback, no tracer.
  (dolist (mode '(:before :after :twice :silent :none :normal))
    (let* ((calls 0) (ends 0)
           (raw (object "end" (lambda () (incf ends) (error "end failed"))))
           (tracer (if (eq mode :none) :null
                       (object "startActiveSpan"
                               (lambda (name options parent callback)
                                 (declare (ignore name options parent))
                                 (when (eq mode :before) (error "before callback"))
                                 (unless (eq mode :silent) (funcall callback raw))
                                 (when (eq mode :twice) (funcall callback raw))
                                 (when (eq mode :after) (error "after callback"))
                                 :tracer-result))))
           (result (multiple-value-list
                    (start-active-span-fail-open tracer "run" (object) :null
                      (lambda (span)
                        (incf calls)
                        (span-call span "end") (span-call span "end")
                        (values :operation-result 42))))))
      (check (equal '(:operation-result 42) result))
      (check (= calls 1))
      (check (= ends (if (member mode '(:before :silent :none)) 0 1)))))
  ;; Even a tracer that swallows or replaces the original error cannot lose it.
  (dolist (mode '(:swallow :replace :propagate :twice :none :before))
    (let* ((original (make-condition 'simple-error :format-control "original operation failure"))
           (calls 0)
           (tracer (if (eq mode :none) :null
                       (object "startActiveSpan"
                               (lambda (name options parent callback)
                                 (declare (ignore name options parent))
                                 (when (eq mode :before) (error "before"))
                                 (if (eq mode :propagate) (funcall callback (object))
                                     (handler-case (funcall callback (object)) (error () nil)))
                                 (when (eq mode :twice)
                                   (handler-case (funcall callback (object)) (error () nil)))
                                 (when (eq mode :replace) (error "replacement tracer error"))))))
           (caught (handler-case
                       (start-active-span-fail-open tracer "fail" (object) :null
                         (lambda (span) (declare (ignore span)) (incf calls) (error original)))
                     (error (condition) condition))))
      (check (eq original caught))
      (check (= calls 1))))
  (check (eq :escaped (catch 'escape
                        (start-active-span-fail-open :null "exit" :null :null
                          (lambda (span) (declare (ignore span)) (throw 'escape :escaped)))))))

(defun test-metrics ()
  (reset-globals)
  (reset-gen-metrics-instruments)
  (reset-optimizer-metrics-instruments)
  (check (eq false (jget (check-metrics-health) "healthy")))
  (check (equal "Global meter not initialized" (aref (jget (check-metrics-health) "issues") 0)))
  (check (eq :null (get-or-create-gen-metrics-instruments)))
  (check (eq :null (get-or-create-optimizer-metrics-instruments)))
  (multiple-value-bind (meter-a observations-a creations-a) (scripted-meter)
    (multiple-value-bind (meter-b observations-b creations-b) (scripted-meter)
      (set-global "meter" meter-a)
      (check (equal "Metrics instruments not created despite available meter"
                    (aref (jget (check-metrics-health) "issues") 0)))
      (let ((a (get-or-create-gen-metrics-instruments))
            (b (get-or-create-gen-metrics-instruments meter-b)))
        (check (eq a (get-or-create-gen-metrics-instruments meter-a)))
        (check (eq true (jget (check-metrics-health) "healthy")))
        (check (= 31 (length (funcall creations-a))))
        (check (= 31 (length (funcall creations-b))))
        (check (not (eq a b)))
        (check (equal "ms" (jget (third (first (funcall creations-a))) "unit")))
        ;; Deliberately store non-default sampling/categories: helpers must not
        ;; invent enforcement that is absent from the source.
        (update-metrics-config (object "maxLabelLength" 5 "samplingRate" 0 "enabledCategories" #()))
        (record-generation-metric a 12 false :signature-name "signature" :ai-service "local"
                                  :custom-labels (object "model" "model-name" "drop" :null "flag" false))
        (record-generation-metric b 24 true)
        (check (= 3 (length (funcall observations-a))))
        (check (= 2 (length (funcall observations-b))))
        (let ((event (first (funcall observations-a))))
          (check (equal "ax_gen_generation_duration_ms" (first event)))
          (check (equal "record" (second event)))
          (check (= 12 (third event)))
          (check (equal "signa" (jget (fourth event) "signature")))
          (check (equal "model" (jget (fourth event) "model")))
          (check (equal "false" (jget (fourth event) "flag")))
          (check (not (nth-value 1 (gethash "drop" (fourth event))))))
        (check (equal "add" (second (second (funcall observations-a)))))
        (update-metrics-config (default-metrics-config))
        (record-multi-step-metric a 3 3)
        (record-validation-error-metric a "validation")
        (record-refusal-error-metric a)
        (record-error-correction-metric a 1 true 3)
        (record-error-correction-metric a 3 false 3)
        (record-function-calling-metric a true 2 true :function-error-correction true)
        (record-field-processing-metric a 2 3)
        (record-streaming-metric a true 4 :finalization-duration 5)
        (record-samples-metric a 2 true :result-picker-latency 6)
        (record-signature-complexity-metrics a 1 2 3 4)
        (dolist (kind '("prompt_render" "extraction" "state_creation" "memory_update"))
          (record-performance-metric a kind 7))
        ;; Every generation factory instrument was observed through a public helper.
        (dolist (creation (funcall creations-a))
          (check (find (second creation) (funcall observations-a) :key #'first :test #'equal)
                 (format nil "No observation for ~A" (second creation))))
        (check (= 2 (length (funcall observations-b))))
        (set-global "meter" (scripted-meter))
        (check (eq false (jget (check-metrics-health) "healthy")))
        (reset-gen-metrics-instruments)
        (check (not (eq a (get-or-create-gen-metrics-instruments meter-a)))))
      (let ((a (get-or-create-optimizer-metrics-instruments meter-a))
            (b (get-or-create-optimizer-metrics-instruments meter-b)))
        (check (not (eq a b)))
        (check (eq b (get-or-create-optimizer-metrics-instruments)))
        (check (eq a (get-or-create-optimizer-metrics-instruments meter-a)))
        (check (= 64 (length (funcall creations-b))))
        (record-optimization-metric a 50 false "gepa")
        (record-convergence-metric a 3 0.9d0 0.2d0 1 "gepa")
        (record-early-stopping-metric a "target" "gepa")
        (record-resource-usage-metric a 100 0.02d0 "gepa" :memory-usage 0)
        (record-optimization-duration-metric a 50 "gepa")
        (record-teacher-student-metric a 10 0.1d0 "gepa")
        (record-checkpoint-metric a "save" 1 true "gepa")
        (record-checkpoint-metric a "load" 2 false "gepa")
        (record-pareto-metric a 2 3 "gepa" :hypervolume 0)
        (record-program-complexity-metric a 1 2 3 4 "gepa")
        (dolist (kind '("evaluation" "demo_generation" "metric_computation"))
          (record-optimizer-performance-metric a kind 5 "gepa"))
        (record-optimizer-configuration-metric a "gepa" :target-score 0 :max-rounds 0)
        (dolist (creation (funcall creations-a))
          (when (search "ax_optimizer_" (second creation))
            (check (find (second creation) (funcall observations-a) :key #'first :test #'equal)
                   (format nil "No observation for ~A" (second creation)))))
        (check (= 2 (length (funcall observations-b))))
        (record-optimization-metric b 60 true "gepa")
        (check (= 4 (length (funcall observations-b))))
        (reset-optimizer-metrics-instruments)
        (check (eq :null (get-or-create-optimizer-metrics-instruments)))
        (check (not (eq a (get-or-create-optimizer-metrics-instruments meter-a)))))))
  (check (eq :null (get-or-create-gen-metrics-instruments (scripted-meter :fail-create t))))
  (check (eq :null (get-or-create-optimizer-metrics-instruments (scripted-meter :fail-create t))))
  (let ((instruments (get-or-create-gen-metrics-instruments (scripted-meter :fail-record t))))
    (check (eq :null (record-generation-metric instruments 1 true)))
    (check (eq :null (telemetry-call (jget instruments "generationRequestsCounter") "add" 1 (object)))))
  (multiple-value-bind (meter observations) (scripted-meter)
    (let ((instruments (get-or-create-gen-metrics-instruments meter)))
      (record-generation-metric instruments 0 true :signature-name "" :ai-service "" :model "")
      (check (equal "{\"success\":\"true\"}" (encode-json (fourth (first (funcall observations))))))
      (record-streaming-metric instruments false 0 :finalization-duration 0)
      (record-field-processing-metric instruments 0 0)
      (record-validation-error-metric instruments "not-validation")
      (record-performance-metric instruments "not-performance" 1)
      (check (= 2 (length (funcall observations))))
      ;; A broken histogram must not suppress the later request/error counters.
      (setf (gethash "generationLatencyHistogram" instruments)
            (object "record" (lambda (&rest args) (declare (ignore args)) (error "broken histogram"))))
      (record-generation-metric instruments 1 false)
      (check (= 4 (length (funcall observations))))))
  (check (eq :null (record-generation-metric :null 1 true))))

(defun run-telemetry-tests ()
  ;; Dynamic bindings leave a caller's native global configuration/caches intact.
  (let ((*checks* 0)
        (axllm::*telemetry-globals* (axllm::%telemetry-default-globals))
        (axllm::*telemetry-metrics-config* (default-metrics-config))
        (axllm::*telemetry-optimizer-metrics-config* (default-optimizer-metrics-config))
        (axllm::*telemetry-gen-by-meter* (make-hash-table :test 'eq))
        (axllm::*telemetry-opt-by-meter* (make-hash-table :test 'eq))
        (axllm::*telemetry-last-optimizer-instruments* :null))
    (test-globals-and-frames)
    (test-spans)
    (test-metrics)
    (format t "~&Telemetry: ~D checks passed.~%" *checks*)
    t))
