;;;; Native ports of dsp/loggers.ts and dsp/optimizerLogging.ts.
;;;; Text and color formats deliberately differ: do not implement text by
;;;; stripping ANSI. These debug loggers display supplied text verbatim.
(in-package #:axllm)

(defun %logger-get (object key)
  (when (member object '(:null :%logger-undefined))
    (error 'ax-error :message "Cannot read a logger property of null or undefined"))
  (jget object key :%logger-undefined))

(defun %logger-optional-get (object key)
  "Property access corresponding to TS optional chaining."
  (jget object key :%logger-undefined))

(defun %logger-truthy (value)
  (not (or (null value) (member value (list :null false :%logger-undefined))
           (and (numberp value) (zerop value)) (equal value ""))))

(defun %logger-text (value)
  "JavaScript interpolation, distinct from JSON.stringify."
  (cond ((eq value :%logger-undefined) "undefined")
        ((stringp value) value)
        ((hash-table-p value) "[object Object]")
        ((%array-p value)
         (format nil "~{~A~^,~}"
                 (map 'list (lambda (x) (if (member x '(:null :%logger-undefined))
                                           "" (%logger-text x))) value)))
        ((typep value 'condition) (princ-to-string value))
        (t (encode-json value))))

(defun %logger-json (value &optional pretty)
  ;; Preserve ordered string keys; pretty JSON uses exactly two spaces.
  (when (eq value :%logger-undefined) (return-from %logger-json "undefined"))
  (if (not pretty) (encode-json value)
      (with-output-to-string (out)
        (labels ((indent (depth) (terpri out) (dotimes (i (* 2 depth)) (write-char #\Space out)))
                 (emit (x depth)
                   (cond
                     ((hash-table-p x)
                      (write-char #\{ out)
                      (loop for key in (%object-keys x) for first = t then nil
                            do (unless first (write-char #\, out))
                               (indent (1+ depth)) (write-string (encode-json key) out)
                               (write-string ": " out) (emit (gethash key x) (1+ depth)))
                      (when (plusp (hash-table-count x)) (indent depth))
                      (write-char #\} out))
                     ((%array-p x)
                      (write-char #\[ out)
                      (loop for item across x for first = t then nil
                            do (unless first (write-char #\, out))
                               (indent (1+ depth)) (emit item (1+ depth)))
                      (when (plusp (length x)) (indent depth))
                      (write-char #\] out))
                     (t (write-string (encode-json x) out)))))
          (emit value 0)))))

(defun %logger-fixed (number digits)
  "ECMAScript toFixed rounding on the supplied binary floating-point value."
  (check-type number real)
  (if (>= (abs number) 1d21) (%logger-text number)
      (let* ((scale (expt 10 digits))
             (rounded (floor (+ (* (abs (rational number)) scale) 1/2))))
        (format nil "~A~D.~V,'0D" (if (minusp number) "-" "")
                (floor rounded scale) digits (mod rounded scale)))))

(defun %logger-color (text color enabled)
  (let ((text (%logger-text text)))
    (if (and enabled color)
        (format nil "~C[~Am~A~C[0m" #\Escape
                (ecase color
                  (:white-bright "97") (:green-bright "92") (:blue-bright "94")
                  ((:red-bright :red) "91") ((:yellow-bright :yellow) "93")
                  (:white "37") (:orange "38;5;208") (:cyan-bright "96")
                  (:magenta-bright "95") (:gray "90") (:green "32")
                  (:cyan "36") (:magenta "35") (:blue "34") (:yellow-dim "33"))
                text #\Escape)
        text)))

(defun %logger-output (message)
  ;; JS UTF-8 stdout replaces a lone surrogate left by a UTF-16 slice.
  ;; Custom callbacks still get the exact sliced string.
  (write-line (map 'string (lambda (c) (if (<= #xd800 (char-code c) #xdfff)
                                         (code-char #xfffd) c)) message)))

(defun %logger-prefix (text limit)
  "First LIMIT UTF-16 code units, as in JS slice/substring."
  (with-output-to-string (out)
    (loop with count = 0 for c across text for code = (char-code c)
          while (< count limit)
          do (if (and (> code #xffff) (= (1+ count) limit))
                 (write-char (code-char (+ #xd800 (ash (- code #x10000) -10))) out)
                 (write-char c out))
             (incf count (if (> code #xffff) 2 1)))))

(defun %logger-text-length (text)
  (loop for c across text sum (if (> (char-code c) #xffff) 2 1)))

(defun %logger-encrypted-p (value)
  (let ((blocks (%logger-get value "thoughtBlocks")))
    (and (%logger-truthy blocks)
         (some (lambda (block) (%logger-truthy (%logger-get block "encrypted"))) blocks))))

(defun format-chat-message (message &key hide-content color)
  "Format one chat message. HIDE-CONTENT hides image/audio payloads only.
COLOR enables the exact ColorLog ANSI palette. Text is never redacted."
  (let ((role (%logger-get message "role")) (body (%logger-get message "content")))
    (flet ((c (text ink) (%logger-color text ink color)))
      (cond
        ((equal role "system")
         (format nil "~A~%~A" (c "[ SYSTEM ]" :magenta-bright) (c body :magenta)))
        ((equal role "function")
         (let ((result (%logger-get message "result")))
           (format nil "~A~%~A" (c "[ FUNCTION RESULT ]" :yellow)
                   (c (if (member result '(:null :%logger-undefined)) "[No result]" result)
                      :yellow-dim))))
        ((equal role "user")
         (with-output-to-string (out)
           (format out "~A~%" (c "[ USER ]" :green-bright))
           (if (stringp body) (write-string (c body :green) out)
               (loop for item across body for first = t then nil
                     for kind = (%logger-get item "type")
                     do (unless first (terpri out))
                        (write-string
                         (cond ((equal kind "text") (c (%logger-get item "text") :green))
                               ((equal kind "image")
                                (c (if hide-content "[Image]"
                                       (format nil "[Image: ~A]" (%logger-text (%logger-get item "image")))) :green))
                               ((equal kind "audio")
                                (c (if hide-content "[Audio]"
                                       (format nil "[Audio: ~A]" (%logger-text (%logger-get item "data")))) :green))
                               (t (c "[Unknown content type]" :gray))) out)))))
        ((equal role "assistant")
         (let ((name (%logger-get message "name")) (calls (%logger-get message "functionCalls")))
           (with-output-to-string (out)
             ;; The reset is BEFORE the optional name and closing bracket.
             (write-string (c "[ ASSISTANT" :cyan-bright) out)
             (when (%logger-truthy name) (format out " ~A" (%logger-text name)))
             (format out " ]~%")
             (when (%logger-truthy body) (format out "~A~%" (c body :cyan)))
             (when (and (%logger-truthy calls) (plusp (length calls)))
               (format out "~A~%" (c "[ FUNCTION CALLS ]" :yellow))
               (loop for call across calls for i from 1
                     for fn = (%logger-get call "function")
                     for params = (%logger-get fn "params")
                     do (when (> i 1) (terpri out))
                        (write-string
                         (c (format nil "~D. ~A(~A) [id: ~A]" i
                                    (%logger-text (%logger-get fn "name"))
                                    (if (stringp params) params (%logger-json params t))
                                    (%logger-text (%logger-get call "id"))) :yellow-dim) out))
               (terpri out))
             (unless (or (%logger-truthy body)
                         (and (%logger-truthy calls) (plusp (length calls))))
               (write-string (c "[No content]" :gray) out)))))
        (t (format nil "~A~%~A" (c "[ UNKNOWN ]" :red-bright)
                   (c (%logger-json message) :gray)))))))

(defun %format-default-log (data color hide-content)
  (let* ((name (%logger-get data "name")) (value (%logger-get data "value"))
         (divider (%logger-color (format nil "~A~A" (make-string 60 :initial-element #\─)
                                         (if color (string #\Newline) "")) :gray color)))
    (with-output-to-string (out)
      (labels ((c (text ink) (%logger-color text ink color))
               (emit (text &optional ink) (write-string (c text ink) out))
               (line (text &optional ink) (emit text ink) (terpri out))
               (divide () (format out "~%~A~%" divider))
               (heading (text ink &optional prefix) (when prefix (terpri out)) (line text ink))
               (each (fn) (loop for item across value for i from 0
                                do (when (plusp i) (divide)) (funcall fn item i)))
               (thought (item)
                 (let ((label (if (%logger-encrypted-p item) " (redacted)" "")))
                   (c (if color (format nil "[THOUGHT~A]~%~A" label (%logger-text (%logger-get item "thought")))
                          (format nil "[thought~A] ~A" label (%logger-text (%logger-get item "thought")))) :gray)))
               (usage-line (obj key label &optional optional)
                 (let ((x (%logger-get obj key)))
                   (unless (and optional (eq x :%logger-undefined))
                     (format out "~A ~A~%" (c label :white) (%logger-text x))))))
        (cond
          ((equal name "ChatRequestChatPrompt")
           (heading (format nil "[ CHAT REQUEST Step ~A ]" (%logger-text (%logger-get data "step"))) :blue-bright t)
           (format out "~A~%" divider)
           (each (lambda (item i) (declare (ignore i))
                   (emit (format-chat-message item :color color :hide-content hide-content))))
           (format out "~%~A" divider))
          ((equal name "FunctionResults")
           (heading "[ FUNCTION RESULTS ]" :yellow t)
           (unless color (format out "~A~%" divider))
           (each (lambda (item i) (declare (ignore i))
                   (emit (format nil "Function: ~A~%Result: ~A"
                                 (%logger-text (%logger-get item "functionId"))
                                 (%logger-text (%logger-get item "result"))) :yellow-dim))))
          ((equal name "ChatResponseResults")
           (heading "[ CHAT RESPONSE ]" :cyan-bright t)
           (each (lambda (item i) (declare (ignore i))
                   (let ((has-thought (%logger-truthy (%logger-get item "thought")))
                         (has-content (%logger-truthy (%logger-get item "content"))))
                     (when has-thought (emit (thought item)))
                     (when (and has-thought has-content) (terpri out))
                     (when has-content (emit (%logger-get item "content") :cyan))
                     (unless (or has-thought has-content) (emit "[No content]" :gray))))))
          ((equal name "ChatResponseStreamingResult")
           (let ((thought (%logger-get value "thought")))
             (if (%logger-truthy thought)
                 (emit (format nil "[THOUGHT]~%~A" (%logger-text thought)) :gray)
                 (emit (or (loop for key in '("delta" "content") for x = (%logger-get value key)
                                 when (%logger-truthy x) return x) "") :cyan-bright))))
          ((equal name "ChatResponseStreamingDoneResult")
           (heading "[ CHAT RESPONSE ]" :cyan-bright t)
           (when color (format out "~A~%" divider))
           (when (%logger-truthy (%logger-get value "content")) (emit (%logger-get value "content") :cyan-bright))
           (when (%logger-truthy (%logger-get value "thought")) (terpri out) (emit (thought value)))
           (when (%logger-truthy (%logger-get value "functionCalls"))
             (emit (%logger-json (%logger-get value "functionCalls") t) :cyan-bright)))
          ((member name '("FunctionError" "ValidationError") :test #'equal)
           (heading (format nil "[ ~A ERROR #~A ]" (if (equal name "FunctionError") "FUNCTION" "VALIDATION")
                            (%logger-text (%logger-get data "index"))) :red-bright t)
           (format out "~A~%" divider)
           (line (%logger-get data "fixingInstructions") :white)
           (emit (format nil "Error: ~A" (%logger-text (%logger-get data "error"))) :red))
          ((equal name "ResultPickerUsed")
           (heading "[ RESULT PICKER ]" :green-bright)
           (format out "~A~%" divider)
           (emit (format nil "Selected sample ~A of ~A (~Ams)"
                         (1+ (%logger-get data "selectedIndex")) (%logger-text (%logger-get data "sampleCount"))
                         (%logger-fixed (%logger-get data "latency") 2)) :green))
          ((equal name "Notification")
           (heading (format nil "[ NOTIFICATION ~A ]" (%logger-text (%logger-get data "id"))) :gray)
           (format out "~A~%" divider) (emit value :white))
          ((equal name "EmbedRequest")
           (heading (format nil "[ EMBED REQUEST ~A ]" (%logger-text (%logger-get data "embedModel"))) :orange)
           (format out "~A~%" divider)
           (each (lambda (text i)
                   (emit (format nil "Text ~D: ~A~A" (1+ i) (%logger-prefix text 100)
                                 (if (> (%logger-text-length text) 100) "..." "")) :white))))
          ((equal name "EmbedResponse")
           (heading (format nil "[ EMBED RESPONSE (~A embeddings) ]" (%logger-text (%logger-get data "totalEmbeddings"))) :orange)
           (format out "~A~%" divider)
           (each (lambda (item i)
                   (emit (format nil "Embedding ~D: [~{~A~^, ~}~A] (length: ~A)" (1+ i)
                                 (map 'list #'%logger-text (%logger-get item "sample"))
                                 (if (%logger-truthy (%logger-get item "truncated")) ", ..." "")
                                 (%logger-text (%logger-get item "length"))) :white))))
          ((equal name "ChatResponseUsage")
           (line (format nil "~%[ CHAT RESPONSE USAGE ]") :green-bright)
           (usage-line value "ai" "AI:") (usage-line value "model" "Model:")
           (loop for (key label) in '(("systemPromptCharacters" "System Prompt Characters:")
                                     ("exampleChatContextCharacters" "Example Chat Context Characters:")
                                     ("mutableChatContextCharacters" "Mutable Chat Context Characters:")
                                     ("chatContextCharacters" "Chat Context Characters:")
                                     ("totalPromptCharacters" "Total Prompt Characters:"))
                 do (usage-line value key label t))
           (let ((tokens (%logger-get value "tokens")))
             (when (%logger-truthy tokens)
               (usage-line tokens "totalTokens" "Total Tokens:")
               (usage-line tokens "promptTokens" "Prompt Tokens:")
               (usage-line tokens "completionTokens" "Completion Tokens:")
               (loop for (key label) in '(("thoughtsTokens" "Thoughts Tokens:") ("reasoningTokens" "Reasoning Tokens:")
                                         ("cacheCreationTokens" "Cache Creation Tokens:") ("cacheReadTokens" "Cache Read Tokens:")
                                         ("serviceTier" "Service Tier:"))
                     do (usage-line tokens key label t))))
           (unless (eq (%logger-get value "estimatedCost") :%logger-undefined)
             (format out "~A $~A~%" (c "Estimated Cost:" :white) (%logger-fixed (%logger-get value "estimatedCost") 6)))
           (emit divider) (unless color (terpri out)))
          ((equal name "ChatResponseCitations")
           (line (format nil "~%[ CHAT RESPONSE CITATIONS ]") :blue-bright)
           (loop for item across value
                 do (emit "- " :white)
                    (line (if (%logger-truthy (%logger-get item "title")) (%logger-get item "title")
                              (%logger-get item "url")) :cyan)
                    (when (%logger-truthy (%logger-get item "description"))
                      (emit "  ") (line (%logger-get item "description") :gray)))
           (emit divider) (unless color (terpri out)))
          (t (emit (%logger-json data t) :gray)))))))

(defun create-default-color-logger (&optional (output #'%logger-output) hide-content)
  "Return a string-callback logger. Callback and formatting failures propagate.
The second optional argument HIDE-CONTENT is a native extension, default off."
  (lambda (data) (funcall output (%format-default-log data t hide-content)) (values)))

(defun create-default-text-logger (&optional (output #'%logger-output) hide-content)
  "Return the text logger. Streaming deltas produce NO output callback."
  (lambda (data)
    (unless (equal (%logger-get data "name") "ChatResponseStreamingResult")
      (funcall output (%format-default-log data nil hide-content)))
    (values)))

(defparameter *default-logger* (create-default-color-logger))

(defun %format-optimizer-text-log (data)
  (let* ((name (%logger-get data "name")) (value (%logger-get data "value"))
         (divider (make-string 60 :initial-element #\─)))
    (flet ((v (key) (%logger-text (%logger-get value key)))
           (j (key &optional pretty) (%logger-json (%logger-get value key) pretty))
           (score (key) (%logger-fixed (%logger-get value key) 3)))
      (cond
        ((equal name "OptimizationStart")
         (format nil "[ OPTIMIZATION START: ~A ]~%~A~%Config: ~A~%Examples: ~A, Validation: ~A~%~A"
                 (v "optimizerType") divider (j "config" t) (v "exampleCount") (v "validationCount") divider))
        ((equal name "RoundProgress")
         (format nil "[ ROUND ~A/~A ]~%Current Score: ~A, Best: ~A~%Config: ~A~%~A"
                 (v "round") (v "totalRounds") (score "currentScore") (score "bestScore") (j "configuration") divider))
        ((equal name "EarlyStopping")
         (format nil "[ EARLY STOPPING at Round ~A ]~%Reason: ~A~%Final Score: ~A~%~A"
                 (v "round") (v "reason") (score "finalScore") divider))
        ((equal name "OptimizationComplete")
         (format nil "[ OPTIMIZATION COMPLETE ]~%~A~%Best Score: ~A~%Best Config: ~A~%Stats: ~A~%~A"
                 divider (score "bestScore") (j "bestConfiguration") (j "stats" t) divider))
        ((equal name "ConfigurationProposal")
         (let ((proposals (%logger-get value "proposals")))
           (format nil "[ CONFIG PROPOSAL: ~A ]~%Count: ~A~%Proposals: ~A ~A~%~A"
                   (v "type") (v "count") (%logger-json (subseq proposals 0 (min 3 (length proposals))) t)
                   (if (> (length proposals) 3) "... (truncated)" "") divider)))
        ((equal name "BootstrappedDemos")
         (let ((demos (%logger-get value "demos")))
           (format nil "[ BOOTSTRAPPED DEMOS ]~%Count: ~A~%Demos: ~A ~A~%~A"
                   (v "count") (%logger-json (subseq demos 0 (min 2 (length demos))) t)
                   (if (> (length demos) 2) "... (truncated)" "") divider)))
        ((equal name "BestConfigFound")
         (format nil "[ BEST CONFIG FOUND ]~%Score: ~A~%Config: ~A~%~A"
                 (score "score") (j "config") divider))
        (t (format nil "[ UNKNOWN OPTIMIZER EVENT ]~%~A~%~A" (%logger-json data) divider))))))

(defun %format-optimizer-color-log (data)
  (let* ((name (%logger-get data "name")) (value (%logger-get data "value"))
         (light (%logger-color (make-string 50 :initial-element #\─) :gray t))
         (heavy (%logger-color (make-string 50 :initial-element #\━) :gray t)))
    (with-output-to-string (out)
      (labels ((c (text ink) (%logger-color text ink t))
               (v (key) (%logger-get value key))
               (emit (text ink) (write-string (c text ink) out))
               (title (text ink &optional prefix suffix)
                 (when prefix (terpri out))
                 (emit "● " ink) (emit text :white-bright)
                 (when suffix (write-char #\Space out) (emit suffix :white))
                 (terpri out))
               (row (label text ink)
                 (format out "  ~A ~A~%" (c label :white) (c text ink)))
               (json-row (label x ink)
                 ;; Undefined JSON is not a string; JS .slice fails here.
                 (when (eq x :%logger-undefined) (error 'ax-error :message "Cannot slice undefined JSON"))
                 (let ((text (%logger-json x)))
                   (format out "  ~A ~A~A~%" (c label :white) (c (%logger-prefix text 80) ink)
                           (if (> (%logger-text-length text) 80) "..." ""))))
               (fixed (key) (%logger-fixed (v key) 3))
               (to-string (x)
                 (when (member x '(:null :%logger-undefined))
                   (error 'ax-error :message "Cannot call toString on null or undefined"))
                 (%logger-text x)))
        (cond
          ((equal name "OptimizationStart")
           (title "Optimization Started" :blue-bright t)
           (format out "~A~%" light)
           (row "Optimizer:" (v "optimizerType") :cyan)
           (format out "  ~A ~A training, ~A validation~%" (c "Examples:" :white)
                   (c (to-string (v "exampleCount")) :green) (c (to-string (v "validationCount")) :green))
           (json-row "Config:" (v "config") :white)
           (format out "~A~%" heavy))
          ((equal name "RoundProgress")
           (let* ((raw (v "configuration")) (config (if (%logger-truthy raw) raw (object)))
                  (parts '()) (current (v "currentScore")) (best (v "bestScore"))
                  (improvement (- current best))
                  (total (cond ((and (numberp (v "totalRounds")) (plusp (v "totalRounds"))) (v "totalRounds"))
                               ((and (numberp (%logger-get config "totalRounds"))
                                     (plusp (%logger-get config "totalRounds"))) (%logger-get config "totalRounds"))
                               (t 0))))
             (when (numberp (%logger-get config "temperature"))
               (push (format nil "T=~A" (%logger-fixed (%logger-get config "temperature") 2)) parts))
             (unless (eq (%logger-get config "bootstrappedDemos") :%logger-undefined)
               (push (format nil "demos=~A" (%logger-text (%logger-get config "bootstrappedDemos"))) parts))
             (when (hash-table-p config)
               (dolist (key (%object-keys config))
                 (when (and (not (member key '("temperature" "bootstrappedDemos" "trialNumber") :test #'equal))
                            (numberp (%logger-get config key)))
                   (push (format nil "~A=~A" key (%logger-fixed (%logger-get config key) 2)) parts))))
             (emit "● " :yellow)
             (emit (format nil "Round ~A/~A" (%logger-text (v "round")) (%logger-text total)) :white-bright)
             (unless (eq (%logger-get config "trialNumber") :%logger-undefined)
               (emit (format nil " [Trial #~A]" (%logger-text (%logger-get config "trialNumber"))) :gray))
             (terpri out)
             (format out "  ~A ~A ~A ~A~A" (c "Score:" :white) (c (fixed "currentScore") :green)
                     (c "(best:" :white) (c (fixed "bestScore") :green-bright) (c ")" :white))
             (cond ((plusp improvement) (emit (format nil " ↑~A" (%logger-fixed improvement 3)) :green-bright))
                   ((minusp improvement) (emit (format nil " ↓~A" (%logger-fixed (abs improvement) 3)) :red)))
             (terpri out)
             (when parts (row "Config:" (format nil "~{~A~^, ~}" (nreverse parts)) :cyan))))
          ((equal name "EarlyStopping")
           (title "Early Stopping" :red t) (format out "~A~%" light)
           (row "Round:" (to-string (v "round")) :yellow)
           (row "Reason:" (v "reason") :yellow)
           (row "Final Score:" (fixed "finalScore") :green)
           (format out "~A~%" heavy))
          ((equal name "OptimizationComplete")
           (title "Optimization Complete" :green t) (format out "~A~%" light)
           (row "Best Score:" (fixed "bestScore") :green-bright)
           (json-row "Best Config:" (v "bestConfiguration") :cyan)
           (let* ((stats (v "stats")) (calls (%logger-optional-get stats "totalCalls"))
                  (successful (%logger-optional-get stats "successfulDemos")))
             (row "Total Calls:" (if (member calls '(:null :%logger-undefined)) "N/A" (%logger-text calls)) :white)
             (row "Success Rate:"
                  (format nil "~A%" (%logger-fixed
                                    (* 100d0 (/ (if (%logger-truthy successful) successful 0)
                                                (max (if (%logger-truthy calls) calls 1) 1))) 1)) :green))
           (when (%logger-truthy (v "explanation"))
             (format out "~%~A~%  ~A~%" (c "📊 Summary:" :blue-bright) (c (v "explanation") :white)))
           (when (%logger-truthy (v "performanceAssessment"))
             (format out "~%~A~%  ~A~%" (c "⚡ Performance:" :yellow-bright) (c (v "performanceAssessment") :white)))
           (when (and (%logger-truthy (v "recommendations")) (plusp (length (v "recommendations"))))
             (format out "~%~A~%" (c "💡 Recommendations:" :green-bright))
             (loop for rec across (v "recommendations") for i from 1
                   do (format out "  ~A ~A~%" (c (format nil "~D." i) :white) (c rec :white))))
           (format out "~A~%" heavy))
          ((equal name "ConfigurationProposal")
           (title (format nil "~A Proposals" (%logger-text (v "type"))) :magenta nil
                  (format nil "(~A)" (%logger-text (v "count"))))
           (let ((proposals (v "proposals")))
             (row "Candidates:"
                  (format nil "~{~A~^, ~}"
                          (loop for p across (subseq proposals 0 (min 2 (length proposals)))
                                collect (if (stringp p) (format nil "\"~A...\"" (%logger-prefix p 40))
                                            (format nil "~A..." (%logger-prefix (%logger-json p) 40))))) :white)))
          ((equal name "BootstrappedDemos")
           (title "Bootstrapped Demos" :cyan nil (format nil "(~A)" (%logger-text (v "count"))))
           (format out "  ~A ~A demonstration examples~%" (c "Generated:" :white) (c (to-string (v "count")) :green)))
          ((equal name "BestConfigFound")
           (title "Best Configuration Found" :green)
           (row "Score:" (fixed "score") :green-bright)
           (json-row "Config:" (v "config") :cyan))
          (t
           (title "Unknown Event" :red)
           (let ((text (%logger-json data)))
             (format out "  ~A~A~%" (c (%logger-prefix text 100) :white)
                     (if (> (%logger-text-length text) 100) "..." "")))))))))

(defun create-default-optimizer-color-logger (&optional (output #'%logger-output))
  "Return the optimizer color logger; callback and formatting errors propagate."
  (lambda (data) (funcall output (%format-optimizer-color-log data)) (values)))

(defun create-default-optimizer-text-logger (&optional (output #'%logger-output))
  "Return the optimizer text logger (not an ANSI-stripped color logger)."
  (lambda (data) (funcall output (%format-optimizer-text-log data)) (values)))

(defparameter *default-optimizer-logger* (create-default-optimizer-color-logger))
