;;;; axllm.asd --- native Ax for Common Lisp
;;;;
;;;; Core owns portable semantics; the native source files provide providers,
;;;; generation, agents, flows, optimization, MCP and event-runtime boundaries.
;;;; The test system rejects failed, unclaimed or missing conformance fixtures.
;;;;
;;;; src/core.lisp is generated. Regenerate it from tools/axir with
;;;;   go run ./cmd/lisp-core --out ../../packages/lisp/src/core.lisp
;;;; and check freshness with
;;;;   go run ./cmd/lisp-core --check
;;;;
(defsystem "axllm"
  :description "Native Ax signatures, providers, typed generation and tools for SBCL"
  :author "Ax contributors"
  :license "Apache-2.0"
  :version "0.1.0"
  :depends-on ("yason" "cl-ppcre" "drakma" "uiop" "cl-base64" "cffi" "puri"
               "ironclad" "local-time" "sqlite" "sb-bsd-sockets")
  :serial t
  :components ((:module "src"
                :serial t
                :components ((:file "package")
                             (:file "json")
                             (:file "core-runtime")
                             (:file "core")
                             (:file "signature")
                             (:file "builder")
                             (:file "template")
                             (:file "prompt")
                             (:file "validation")
                             (:file "telemetry")
                             (:file "loggers")
                             (:file "string-util")
                             (:file "ai")
                             (:file "stream")
                             (:file "provider")
                             (:file "session")
                             (:file "tools")
                             (:file "gen")
                             (:file "refine")
                             (:file "synth")
                             (:file "evaluate")
                             (:file "optimize")
                             (:file "agent-runtime")
                             (:file "agent")
                             (:file "flow")
                             (:file "event")
                             (:file "event-store-sqlite")
                             (:file "mcp")
                             (:file "ucp-schema")
                             (:file "mcp-chat")
                             (:file "mcp-app")
                             (:file "mcp-auth")
                             (:file "ucp-signing")
                             (:file "mcp-transport-stdio")
                             (:file "mcp-transport-http")
                             (:file "mcp-transport-websocket")
                             (:file "mcp-record"))))
  :in-order-to ((test-op (test-op "axllm/tests"))))

(defsystem "axllm/jiti"
  :description "Optional Ax proposer callback for Jiti; no Jiti dependency"
  :license "Apache-2.0"
  :depends-on ("axllm")
  :components ((:file "src/jiti")))

(defsystem "axllm/tests"
  :description "Shared Core fixtures and native provider, generation, tool and adapter tests"
  :license "Apache-2.0"
  :depends-on ("axllm/jiti" "sb-bsd-sockets" "sb-posix" "usocket" "websocket-driver-client")
  :serial t
  :components ((:module "tests"
                :serial t
                :components ((:file "conformance-report")
                             (:file "signature")
                             (:file "builder")
                             (:file "json")
                             (:file "core-primitives")
                             (:file "template")
                             (:file "prompt")
                             (:file "validation")
                             (:file "telemetry")
                             (:file "loggers")
                             (:file "string-util")
                             (:file "provider")
                             (:file "gen-conformance")
                             (:file "ai-runtime")
                             (:file "ai-conformance")
                             (:file "refine")
                             (:file "synth")
                             (:file "optimize-conformance")
                             (:file "optimize-runtime")
                             (:file "agent-runtime")
                             (:file "agent-conformance")
                             (:file "flow-runtime")
                             (:file "flow-conformance")
                             (:file "mcp-conformance")
                             (:file "mcp-runtime")
                             (:file "mcp-chat")
                             (:file "ucp-schema")
                             (:file "ucp-signing-conformance")
                             (:file "event-conformance")
                             (:file "event-store-conformance")
                             (:file "jiti"))))
  :perform (test-op (op system)
                    (declare (ignore op system))
                    (uiop:symbol-call :axllm/conformance :run-report-tests)
                    (uiop:symbol-call :axllm/conformance :start-report
                                      (uiop:symbol-call :axllm/tests :conformance-directory))
                    (unless (uiop:symbol-call :axllm/tests :run-all-tests)
                      (error "Ax signature/schema conformance failed."))
                    (uiop:symbol-call :axllm/tests :run-builder-tests)
                    (uiop:symbol-call :axllm/tests :run-json-tests)
                    (unless (uiop:symbol-call :axllm/tests/core-primitives :run-core-primitive-tests)
                      (error "Ax Core primitive tests failed."))
                    (uiop:symbol-call :axllm/template-tests :run-template-tests)
                    (uiop:symbol-call :axllm/tests :run-prompt-tests)
                    (uiop:symbol-call :axllm/tests :run-validation-tests)
                    (uiop:symbol-call :axllm/telemetry-tests :run-telemetry-tests)
                    (uiop:symbol-call :axllm/logger-tests :run-logger-tests)
                    (unless (uiop:symbol-call :axllm/tests/string-util :run-string-util-tests)
                      (error "Ax string utility tests failed."))
                    (multiple-value-bind (passed failed)
                        (uiop:symbol-call :axllm :run-provider-tests)
                      (declare (ignore passed))
                      (unless (zerop failed) (error "Ax provider tests failed.")))
                    (multiple-value-bind (passed failed unclaimed)
                        (uiop:symbol-call :axllm :run-gen-conformance)
                      (unless (and (plusp passed) (eql failed 0) (eql unclaimed 0))
                        (error "Ax generation conformance failed or is incomplete.")))
                    (uiop:symbol-call :axllm/ai-tests :run-ai-runtime-tests-or-die)
                    (multiple-value-bind (passed failed unclaimed)
                        (uiop:symbol-call :axllm/ai-conformance :run-ai-conformance-tests)
                      (unless (and (plusp passed) (eql failed 0) (eql unclaimed 0))
                        (error "Ax AI conformance failed or is incomplete.")))
                    (dolist (runner '(:run-refine-tests :run-synth-tests))
                      (multiple-value-bind (passed failed) (uiop:symbol-call :axllm runner)
                        (declare (ignore passed))
                        (unless (zerop failed) (error "Ax ~A failed." runner))))
                    (multiple-value-bind (passed failed)
                        (uiop:symbol-call :axllm/optimize-runtime :run-optimize-runtime-tests)
                      (declare (ignore passed))
                      (unless (zerop failed) (error "Ax optimizer runtime tests failed.")))
                    (multiple-value-bind (passed failed blocked skipped)
                        (uiop:symbol-call :axllm/optimize-conformance :run-optimize-conformance-tests)
                      (unless (and (plusp passed) (eql failed 0) (eql blocked 0) (eql skipped 0))
                        (error "Ax optimizer conformance failed or is incomplete.")))
                    (multiple-value-bind (passed failed skipped)
                        (uiop:symbol-call :axllm/tests-agent :run-agent-runtime-tests)
                      (declare (ignore passed))
                      (unless (and (zerop failed) (eql skipped 0))
                        (error "Ax agent runtime tests failed or are incomplete.")))
                    (unless (uiop:symbol-call :axllm/flow-runtime-tests :run-flow-runtime-tests)
                      (error "Ax flow runtime tests failed."))
                    (unless (uiop:symbol-call :axllm/flow-tests :run-flow-conformance-tests)
                      (error "Ax flow conformance failed."))
                    (multiple-value-bind (passed failed blocked partial)
                        (uiop:symbol-call :axllm/tests-agent :run-agent-conformance)
                      (unless (and (plusp passed) (eql failed 0) (eql blocked 0) (eql partial 0))
                        (error "Ax agent conformance failed or is incomplete.")))
                    (uiop:symbol-call :axllm :run-mcp-conformance-tests-or-die)
                    (uiop:symbol-call :axllm :run-mcp-runtime-tests-or-die)
                    (uiop:symbol-call :axllm :run-mcp-chat-tests-or-die)
                    (uiop:symbol-call :axllm :run-ucp-schema-tests-or-die)
                    (uiop:symbol-call :axllm :run-ucp-signing-tests-or-die)
                    (uiop:symbol-call :axllm :run-event-conformance-tests-or-die)
                    (uiop:symbol-call :axllm :run-event-store-conformance-or-die)
                    (uiop:symbol-call :cl-user :run-jiti-tests)
                    (uiop:symbol-call :axllm/conformance :finish-report)))
